spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/cmy1987/config.git
          username: cmy1987-01@163.com
          password: 123456abc
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9999
